# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Arrive5Driver' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Arrive5Driver

pod 'IQKeyboardManagerSwift'
  pod 'MRCountryPicker', '~> 0.0.7'
  pod 'Firebase/Auth','~> 4.0’
    pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'SVProgressHUD'
  pod 'SDWebImage', '~> 4.0'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
#  pod 'CountdownLabel'
pod 'Firebase/Analytics'

# Add the pod for Firebase Cloud Messaging
pod 'Firebase/Messaging'
  # Alamofire
 # pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'
  
  # Crashlytics
  
 

  
  # GoogleMaps
  
  pod 'Alamofire', '~> 4.7'
   pod 'GoogleMaps'
  pod 'GooglePlaces'
end
